#!/usr/bin/env bash
set -e

PATH="/opt/bitnami/kubectl/bin:$PATH"
INIT_FILE=/opt/jradic/kubectl/.init

if [ ! -f ${INIT_FILE} ]; then
    kubectl-init > /dev/null
    touch ${INIT_FILE}
fi

kubectl $@
