#!/usr/bin/env bash
set -e

PATH="/opt/bitnami/kubectl/bin:$PATH"
INIT_FILE=/opt/jradic/kubectl/.init

if [ ! -f ${INIT_FILE} ]; then
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown -R $(id -u):$(id -g) $HOME/.kube
    kubectl-init > /dev/null
    touch ${INIT_FILE}
fi

kubectl $@
